module.exports = {
  GROUP: "GROUP",
  FINAL: "FINAL",
  BRONZE_FINAL: "BRONZE_FINAL",
  SEMI_FINAL: "SEMI_FINAL",
  QUARTER_FINAL: "QUARTER_FINAL",
  TOP_16_FINAL: "TOP_16_FINAL",
  UNKNOWN: "UNKNOWN"
};